"""CSIDH with p = 419: the class-group action, a key exchange, and its checks.

The CSIDH page quotes its numbers from here. p = 4 * 3 * 5 * 7 - 1 = 419 is the
toy prime of Castryck, Lange, Martindale, Panny and Renes. The supersingular
Montgomery curves y^2 = x^3 + A x^2 + x over F_p are acted on by the ideals
above 3, 5 and 7, evaluated with x-only arithmetic and odd-degree Velu
formulas exactly as in the paper's Algorithm 2.

Three independent checks guard the implementation: every curve reached is
supersingular (its group order is p + 1), the action commutes (Alice and
Bob reach the same shared curve), and the orbit of the starting curve has
exactly h(-4p) elements, the class number counted separately from reduced
binary quadratic forms.
"""

from __future__ import annotations

from math import gcd, isqrt

from .arith import Rng, is_prime, legendre

P = 419
PRIMES = (3, 5, 7)
BOUND = 2  # exponents drawn from [-BOUND, BOUND]


def inv(x: int) -> int:
    return pow(x, P - 2, P)


# x-only Montgomery arithmetic in projective (X : Z) coordinates.


def xdbl(X, Z, A):
    a24 = (A + 2) * inv(4) % P
    s, d = (X + Z) ** 2 % P, (X - Z) ** 2 % P
    c = (s - d) % P
    return s * d % P, c * (d + a24 * c) % P


def xadd(X1, Z1, X2, Z2, Xd, Zd):
    u = (X1 - Z1) * (X2 + Z2) % P
    v = (X1 + Z1) * (X2 - Z2) % P
    return Zd * (u + v) ** 2 % P, Xd * (u - v) ** 2 % P


def xmul(k: int, x: int, A: int):
    """x([k]P) as (X : Z); Z = 0 is the point at infinity."""
    if k == 0:
        return (1, 0)
    X0, Z0, X1, Z1 = x, 1, *xdbl(x, 1, A)
    for bit in bin(k)[3:]:
        if bit == "1":
            X0, Z0 = xadd(X0, Z0, X1, Z1, x, 1)
            X1, Z1 = xdbl(X1, Z1, A)
        else:
            X1, Z1 = xadd(X0, Z0, X1, Z1, x, 1)
            X0, Z0 = xdbl(X0, Z0, A)
    return X0, Z0


def affine(XZ):
    X, Z = XZ
    return None if Z % P == 0 else X * inv(Z) % P


def isogeny(A: int, xk: int, ell: int, xq):
    """Odd-degree Velu on a Montgomery curve with kernel generated by x = xk.

    Codomain A' = tau (A - 3 sigma) with tau = prod x_i and sigma = sum(x_i - 1/x_i)
    over the nonzero multiples of the kernel generator; the image of a point
    is x * prod (x x_i - 1) / (x - x_i)."""
    xs = [affine(xmul(i, xk, A)) for i in range(1, ell)]
    assert all(x is not None for x in xs), "kernel point has order ell"
    tau, sigma = 1, 0
    for xi in xs:
        tau = tau * xi % P
        sigma = (sigma + xi - inv(xi)) % P
    A2 = tau * (A - 3 * sigma) % P
    img = None
    if xq is not None:
        num, den = xq, 1
        for xi in xs:
            num = num * (xq * xi - 1) % P
            den = den * (xq - xi) % P
        img = None if den == 0 else num * inv(den) % P
    return A2, img


def action(A: int, exps, rng: Rng) -> int:
    """CSIDH Algorithm 2: apply prod l_i^{e_i} to the curve with coefficient A."""
    e = list(exps)
    while any(e):
        x = rng.below(P)
        rhs = (x ** 3 + A * x * x + x) % P
        s = 1 if legendre(rhs, P) == 1 else -1
        if rhs == 0:
            continue
        S = [i for i, ei in enumerate(e) if ei * s > 0]
        if not S:
            continue
        k = 1
        for i in S:
            k *= PRIMES[i]
        q = affine(xmul((P + 1) // k, x, A))
        for i in S:
            if q is None:
                break
            ell = PRIMES[i]
            kk = affine(xmul(k // ell, q, A))
            if kk is None:
                continue
            A, q = isogeny(A, kk, ell, q)
            k //= ell
            e[i] -= s
    return A


def supersingular(A: int, rng: Rng) -> bool:
    """[p + 1]Q = 0 for random x (points on the curve and on its twist)."""
    for _ in range(8):
        x = rng.below(P)
        if xmul(P + 1, x, A)[1] % P:
            return False
    return True


def class_number(D: int) -> int:
    """h(D) by counting reduced forms ax^2 + bxy + cy^2 of discriminant D < 0."""
    h, a = 0, 1
    while 3 * a * a <= -D:
        for b in range(-a + 1, a + 1):
            if (b * b - D) % (4 * a):
                continue
            c = (b * b - D) // (4 * a)
            if c < a or gcd(gcd(a, abs(b)), c) != 1:
                continue
            if b < 0 and (a == c):
                continue
            h += 1
        a += 1
    return h


def compute() -> dict:
    assert is_prime(P) and P == 4 * 3 * 5 * 7 - 1 and P % 8 == 3
    rng = Rng("isogenylabs/schemes/csidh")

    # The orbit of A = 0 under the three generators.
    orbit, frontier = {0}, [0]
    while frontier:
        nxt = []
        for A in frontier:
            for i in range(len(PRIMES)):
                for s in (1, -1):
                    e = [0] * len(PRIMES)
                    e[i] = s
                    B = action(A, e, rng)
                    if B not in orbit:
                        orbit.add(B)
                        nxt.append(B)
        frontier = nxt
    h = class_number(-4 * P)
    assert len(orbit) == h, (len(orbit), h)
    assert all(supersingular(A, rng) for A in orbit)

    # A key exchange.
    def key():
        return [rng.between(-BOUND, BOUND) for _ in PRIMES]

    a, b = key(), key()
    while not any(a):
        a = key()
    while not any(b):
        b = key()
    A_pub = action(0, a, rng)
    B_pub = action(0, b, rng)
    shared_a = action(B_pub, a, rng)
    shared_b = action(A_pub, b, rng)
    assert shared_a == shared_b
    assert action(A_pub, [-x for x in a], rng) == 0, "the inverse ideal undoes it"
    keyspace = (2 * BOUND + 1) ** len(PRIMES)

    values = {
        "p": str(P), "primes": ", ".join(map(str, PRIMES)),
        "h": str(h), "orbit": str(len(orbit)),
        "bound": str(BOUND), "keyspace": str(keyspace),
        "a": "(" + ", ".join(map(str, a)) + ")",
        "b": "(" + ", ".join(map(str, b)) + ")",
        "A_pub": str(A_pub), "B_pub": str(B_pub), "shared": str(shared_a),
    }
    return {"values": values, "blocks": {}}
